version: "3"

volumes:
  db:
  logs:
  upload:

services:
  postgres:
    build: ./postgresdb
    env_file:
      - .env
    image: kostik1986/rs-app-postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - network
    restart: always

  nodes:
    build: .
    image: kostik1986/rs-app-node
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
    restart: always
    depends_on:
      - postgres
    volumes:
      - upload:/rs-app/upload
      - logs:/rs-app/logs
      - ./src:/app/src
    networks:
      - network

networks:
  network:
    driver: bridge
