version: "3"

volumes:
  db:
  logs:

services:
  notes:
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
    restart: always
    depends_on:
      - postgres
    volumes:
      - logs:/app/logs
      - ./:/app
    networks:
      - network

  postgres:
    build: ./postgersdb
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db:/var/lib
    networks:
      - network
networks:
  network:
    driver: bridge
